
package Vistas;

import vacunar23_AccesoADatos.Conexion.LaboratorioData;
import vacunar23_Entidades.Laboratorio;

public class admin_lab_BuscarxCuit extends javax.swing.JInternalFrame {
    //Declaración de atributos
    private LaboratorioData buscar_labData=new LaboratorioData();//para acceder al metodo buscar
    private Laboratorio lab= new Laboratorio();//para guardar los datos del laboratorio que necesite (es mi modelo)
    
    private Admin_Laboratorio_Principal jframePrincipal; //para hacer referencia a la ventana principal de laboratorio

    
    public admin_lab_BuscarxCuit() {
        initComponents();
    }

    //el siguiente método permite el vínculo con la ventana principal
    /*
        en el envento del boton buscar por cuit pondremos:
        admin_lab_BuscarxCuit buscarCuit = new admin_lab_BuscarxCuit(this); 
        y si éste método no está aquí no habrá referencia y dará error esa línea anterior
    */
     public admin_lab_BuscarxCuit(Admin_Laboratorio_Principal jframePrincipal) {
        this.jframePrincipal = jframePrincipal;        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIngresarCuit = new javax.swing.JLabel();
        jbBuscarCuit = new javax.swing.JButton();
        jtCuit = new javax.swing.JTextField();

        jlIngresarCuit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlIngresarCuit.setText("Ingrese el CUIT del laboratorio:");

        jbBuscarCuit.setText("Buscar");
        jbBuscarCuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarCuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jlIngresarCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jbBuscarCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIngresarCuit)
                    .addComponent(jtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jbBuscarCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /*-----------------------------EVENTOS-------------------------------------*/
    ///Botón Buscar
    private void jbBuscarCuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarCuitActionPerformed
        String cuit= jtCuit.getText();
        long cuitparseado = Long.parseLong(cuit);//parseo porque el método espera un lon y no un string
        lab = buscar_labData.buscarLaboratorioXCUIT(cuitparseado);//almaceno el lab que encuentre el méotodo de laboratorioData        
        //verifico en el if si encontró un lab para cerrar esta ventana e imprimir el lab encontrado en la tabla

        if(lab!=null){
            // Llama al método para actualizar la JTable en el JFrame principal
            jframePrincipal.actualizarJTable(lab);//método de la ventana principal que actualiza la tabla
            this.dispose();//cierra ésta ventana en caso de encontrar el laboratorio
        }
    }//GEN-LAST:event_jbBuscarCuitActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbBuscarCuit;
    private javax.swing.JLabel jlIngresarCuit;
    private javax.swing.JTextField jtCuit;
    // End of variables declaration//GEN-END:variables
}
