
package Vistas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

public class Vacunatorio extends javax.swing.JFrame {

    public Vacunatorio() {
        initComponents();
        
        //JButton jbIconVacuna;
        /*
        jbIconVacuna = new JButton(new ImageIcon("IconVacuna.png"));
                
        jbIconVacuna.setBounds(0, 0, 130, 130);
       
       */ 
        
        
        /*
        // Creo una instancia de una variable "im" de tipo "ImagenIcon" donde le paso la URL del paquete del proyecto donde está ubicada la imagen
        ImageIcon im = new ImageIcon("/iconos/IconVacuna.png");
        
        Icon i = new ImageIcon(im.getImage().getScaledInstance(jbIconVacuna.getWidth(), jbIconVacuna.getHeight(), Image.SCALE_DEFAULT));
        
        jbIconVacuna.setIcon(i);
        add(jbIconVacuna);
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jbIconVacuna = new javax.swing.JButton();
        jbIconLaboratorio = new javax.swing.JButton();
        jbIconCiudadano = new javax.swing.JButton();
        jbIconCitas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setPreferredSize(new java.awt.Dimension(700, 700));

        jbIconVacuna.setText("Vacunas");
        jbIconVacuna.setPreferredSize(new java.awt.Dimension(30, 15));
        jbIconVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIconVacunaActionPerformed(evt);
            }
        });

        jbIconLaboratorio.setText("Laboratorios");
        jbIconLaboratorio.setPreferredSize(new java.awt.Dimension(30, 15));
        jbIconLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIconLaboratorioActionPerformed(evt);
            }
        });

        jbIconCiudadano.setText("Ciudadano");
        jbIconCiudadano.setPreferredSize(new java.awt.Dimension(30, 15));
        jbIconCiudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIconCiudadanoActionPerformed(evt);
            }
        });

        jbIconCitas.setText("Citas");
        jbIconCitas.setPreferredSize(new java.awt.Dimension(30, 15));
        jbIconCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIconCitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbIconCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbIconLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbIconVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbIconCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(577, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jbIconVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbIconLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbIconCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jbIconCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIconVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIconVacunaActionPerformed
        // CLICK EN VACUNAS
        
        escritorio.removeAll();
        escritorio.repaint();
        
        VacunasView vac = new VacunasView();
        vac.setVisible(true);
        
        escritorio.add(vac);
    }//GEN-LAST:event_jbIconVacunaActionPerformed

    private void jbIconLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIconLaboratorioActionPerformed
        // CLICK EN LABORATORIO
        
        escritorio.removeAll();
        escritorio.repaint();
        
        Admin_Laboratorio_Principal lab = new Admin_Laboratorio_Principal();
        lab.setVisible(true);        
        escritorio.add(lab);
    }//GEN-LAST:event_jbIconLaboratorioActionPerformed

    private void jbIconCiudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIconCiudadanoActionPerformed
        // CLICK EN CIUDADANO
        
        escritorio.removeAll();
        escritorio.repaint();
        
        CiudadanoView ciu = new CiudadanoView();
        ciu.setVisible(true);
        escritorio.add(ciu);
    }//GEN-LAST:event_jbIconCiudadanoActionPerformed

    private void jbIconCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIconCitasActionPerformed
        // CLICK EN CITAS
        
        escritorio.removeAll();
        escritorio.repaint();
        
        CitaView cita = new CitaView();
        cita.setVisible(true);
        escritorio.add(cita);
    }//GEN-LAST:event_jbIconCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vacunatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vacunatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vacunatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vacunatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vacunatorio().setVisible(true);
            }
        });
    }
    
            /*---------- Método para ajustar el tamaño del ícono en el botón --------*/
        
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbIconCitas;
    private javax.swing.JButton jbIconCiudadano;
    private javax.swing.JButton jbIconLaboratorio;
    private javax.swing.JButton jbIconVacuna;
    // End of variables declaration//GEN-END:variables



}
